POST http://localhost:3000/register HTTP/1.1
content-type:application/json

{
    "name": "a1",
    "username": "a1",
    "email": "a1@gmail.com",
    "password": "000"
}

###
POST http://localhost:3000/login HTTP/1.1
content-type:application/json

{
    "email": "a1@gmail.com",
    "password": "000"
}

###
# To get the token, run the /login request above and copy the token value here.
GET http://localhost:3000/get_user_and_profile
content-type:application/json

{
    "token" : "be8477c4a294c7e024808cb19bf535d62e5640747f67e443ff52c9b0532841d8"
}


### 
POST http://localhost:3000/update_profile_data
Content-Type: application/json

{
    "token":"be8477c4a294c7e024808cb19bf535d62e5640747f67e443ff52c9b0532841d8",
    "bio":"",
    "currentPost":"CTO",
    "pastWork":[
        {
            "company":"Microsoft",
            "position":"CTO",
            "years":"2+"
        }
    ],
    "education":[
        {
            "school":"IIT",
            "degree":"BCA",
            "fieldOfStudy":"2015-2019"
        }
    ]
}